### PR TITLE
Default to KUBE_EDITOR and keep EDITOR as fallback

### PR DESCRIPTION
**Pull request by jose-rojas0**
This PR addresses #14

### CODE REVIEW

**Comment by rajatjindal** [comment]
thanks a lot for PR @jarojasm95 

one small request: can u move the logic to get the editor to a separate function? thanks

**Comment by jose-rojas0** [comment]
@rajatjindal done 👍

**Comment by rajatjindal** [comment]
thank you very much. 

I do not want to  sound very  picky, so this change suggestion is optional. (I can do it if you are short on time to make this change)

From

```
func getEditor() string {
	editorFromEnv := os.Getenv("KUBE_EDITOR")
	if editorFromEnv == "" {
		editorFromEnv = os.Getenv("EDITOR")
		if editorFromEnv == "" {
			editorFromEnv = defaultEditor
		}
	}
	return editorFromEnv
}

```

To
```
func getEditor() string {
	if os.Getenv("KUBE_EDITOR") != "" {
           return os.Getenv("KUBE_EDITOR")
        }
        

	if os.Getenv("EDITOR") != "" {
           return  os.Getenv("EDITOR") 
        }
        
         return defaultEditor
}
```

this helps with readability.

**Comment by jose-rojas0** [comment]
thanks for the feedback! makes total sense - I was more focused on "make it work" when writing it since I'm a total `go` noob

**Review by rajatjindal — APPROVED** [review]

**Comment by rajatjindal** [comment]
thanks a lot for your contribution.

**Pull request merged**
